services:
  client:
    build:
      context: ./npz_viewer_client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"

networks:
  default:
    name: npz_viewer_network
