services:
  client:
    build:
      context: ./npz_viewer_client
      dockerfile: Dockerfile
    container_name: client-dev
    ports:
      - "3000:3000"
    volumes:
      - ./npz_viewer_client:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

networks:
  default:
    name: npz_viewer_network
